version: "3.8"

services:
  # FastAPI AI 서비스
  ai_app:
    # build 컨텍스트를 AI 폴더로 지정합니다.
    build:
      context: ./AI
      dockerfile: Dockerfile
    image: localpiece-ai-app
    container_name: localpiece-ai-container
    # 서버에 직접 생성할 .env 파일을 읽어들입니다.
    env_file:
      - ./.env
    # 다중 워커 실행으로 병목 현상을 방지합니다.
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4
    restart: always

  # Nginx 리버스 프록시
  nginx:
    image: nginx:latest
    container_name: localpiece-ai-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 아래에서 생성할 nginx.conf 파일을 마운트합니다.
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # SSL 인증서를 위한 볼륨 마운트입니다.
      - /etc/letsencrypt:/etc/letsencrypt
    # ai_app이 실행된 후에 Nginx가 시작됩니다.
    depends_on:
      - ai_app
    restart: always