version: "3.8"

services:
  # 1. Spring Boot App 서비스
  app:
    # ⬇️ Docker Hub에서 이미지를 가져오도록 명확하게 지정합니다.
    image: 225989336583.dkr.ecr.ap-northeast-2.amazonaws.com/localpiece-app
    # 컨테이너 이름 지정
    container_name: localpiece-app-container
    # .env 파일에 정의된 환경 변수를 컨테이너 내부로 전달
    env_file:
      - ./.env
    # 항상 재시작
    restart: always

  # 2. Nginx 서비스
  nginx:
    # 공식 Nginx 최신 이미지를 사용
    image: nginx:latest
    container_name: localpiece-nginx-container
    ports:
      # 외부의 80 포트를 Nginx 컨테이너의 80 포트로 연결
      - "80:80"
    volumes:
      # 현재 폴더의 nginx.conf 파일을 컨테이너 내부의 설정 파일 경로에 덮어쓰기
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    # app 서비스가 먼저 시작된 후에 nginx 서비스를 시작
    depends_on:
      - app
    restart: always