name: Deploy AI

on:
  push:
    branches:
      - feature/AI-CMG
    paths:
      - "AI/**"
      - ".github/workflows/deploy-ai.yml"
      - "docker-compose-ai.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to OCI Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # 프로젝트 폴더로 이동 (없으면 git clone)
          if [ ! -d "my-ai-project" ]; then
            git clone https://github.com/YOUR_USERNAME/YOUR_REPOSITORY.git my-ai-project
          fi
          cd my-ai-project
          
          # 최신 코드 받아오기
          git pull
          
          # 기존 컨테이너 중지 및 삭제
          if [ "$(docker ps -q -f name=ai-blog-server)" ]; then
            docker stop ai-blog-server
            docker rm ai-blog-server
          fi
          
          # 새 도커 이미지 빌드 (Dockerfile이 있는 위치에서 실행)
          docker build -t ai-blog-app .
          
          # 새 도커 컨테이너 실행
          # 포트 변경을 반영하여 8000번 포트로 실행
          docker run -d --name ai-blog-server -p 8000:8000 ai-blog-app

     